// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGoLmbxsuZvAgYs0caqvaSf1vQH7s1qLg',
    appId: '1:1064705163166:web:b0a4faf267d939bfbde08f',
    messagingSenderId: '1064705163166',
    projectId: 'ather-8888',
    authDomain: 'ather-8888.firebaseapp.com',
    storageBucket: 'ather-8888.firebasestorage.app',
    measurementId: 'G-9XV5LQG3HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5rweugwKppgoKUhm9gNkzyCzod_iQwi0',
    appId: '1:1064705163166:android:e4f996856990e3dbbde08f',
    messagingSenderId: '1064705163166',
    projectId: 'ather-8888',
    storageBucket: 'ather-8888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDREnPrWzbZMxgBUeJy9QRZEY0dIe2grPU',
    appId: '1:1064705163166:ios:eb24df22aba2791fbde08f',
    messagingSenderId: '1064705163166',
    projectId: 'ather-8888',
    storageBucket: 'ather-8888.firebasestorage.app',
    iosBundleId: 'com.iappsnet.athar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDREnPrWzbZMxgBUeJy9QRZEY0dIe2grPU',
    appId: '1:1064705163166:ios:7b9ce5184fdcc3fdbde08f',
    messagingSenderId: '1064705163166',
    projectId: 'ather-8888',
    storageBucket: 'ather-8888.firebasestorage.app',
    iosBundleId: 'com.example.athar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGoLmbxsuZvAgYs0caqvaSf1vQH7s1qLg',
    appId: '1:1064705163166:web:139e272f0e452ffbbde08f',
    messagingSenderId: '1064705163166',
    projectId: 'ather-8888',
    authDomain: 'ather-8888.firebaseapp.com',
    storageBucket: 'ather-8888.firebasestorage.app',
    measurementId: 'G-PBEY2M4787',
  );

}